
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adm;

import DAO.PessoaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import Modelo.Pessoa;

/**
 *
 * @author Aluno
 */
public class PessoaManter extends javax.swing.JFrame {

    /**
     * Creates new form PessoaManter
     */
    private List<Pessoa> lista; 
    private Integer posicao;
    public PessoaManter() {
        initComponents();
        PessoaDAO dao = new PessoaDAO();
        lista = dao.listar();
        posicao = 0;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BPrimeiro = new javax.swing.JButton();
        BAnterior = new javax.swing.JButton();
        BProximo = new javax.swing.JButton();
        BUltimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        SCombocaixa = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        BCadastra = new javax.swing.JButton();
        BExcluir = new javax.swing.JButton();
        BConsultar = new javax.swing.JButton();
        BLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnListagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Navegação"));

        BPrimeiro.setText("Primeiro");
        BPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPrimeiroActionPerformed(evt);
            }
        });

        BAnterior.setText("Anterior");
        BAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnteriorActionPerformed(evt);
            }
        });

        BProximo.setText("Próximo");
        BProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProximoActionPerformed(evt);
            }
        });

        BUltimo.setText("Ultimo");
        BUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BPrimeiro)
                .addGap(18, 18, 18)
                .addComponent(BAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPrimeiro)
                    .addComponent(BAnterior)
                    .addComponent(BProximo)
                    .addComponent(BUltimo))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel1.setText("Código: ");

        jLabel2.setText("Nome: ");

        jLabel3.setText("Sexo: ");

        txtcod.setEditable(false);
        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });

        txtnome.setText(" ");

        SCombocaixa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha", "M", "F" }));
        SCombocaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCombocaixaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ação"));

        BCadastra.setText("Cadastrar");
        BCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastraActionPerformed(evt);
            }
        });

        BExcluir.setText("Excluir");
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        BConsultar.setText("Consultar");
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        BLimpar.setText("Limpar");
        BLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimparActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BConsultar)
                .addGap(18, 18, 18)
                .addComponent(BLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCadastra)
                    .addComponent(BExcluir)
                    .addComponent(BConsultar)
                    .addComponent(BLimpar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Informações pessoais");

        btnListagem.setText("Ir até lista");
        btnListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(btnListagem))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SCombocaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(123, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SCombocaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnListagem)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPrimeiroActionPerformed
        // TODO add your handling code here:
        if(lista.size()>0){
            Pessoa pessoa = lista.get(0);
            txtcod.setText(pessoa.getCodigo().toString());
            txtnome.setText(pessoa.getNome());
            if(pessoa.getSexo().equals("F")){
                SCombocaixa.setSelectedIndex(1);
            }else if(pessoa.getSexo().equals("M")){
                SCombocaixa.setSelectedIndex(2);
            }
        }
    }//GEN-LAST:event_BPrimeiroActionPerformed

    private void BCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastraActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa();
        if(txtnome.getText().isEmpty() || SCombocaixa.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
        }else{
            p.setNome(txtnome.getText());
            p.setSexo(SCombocaixa.getSelectedItem().toString());
            //intancia a classe de acesso a dados PessoaDAO
            PessoaDAO dao = new PessoaDAO();
            //chama o inserir
            boolean deucerto = dao.inserir(p);
            if (deucerto == true) {
                JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar!");
            }
            lista.add(p);
            posicao ++;
            Limpar();
            }
    }//GEN-LAST:event_BCadastraActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
      // TODO add your handling code here:
            PessoaDAO dao = new PessoaDAO();
            boolean deucerto = dao.excluir(lista.get(posicao));
            if(deucerto==true){
                JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso");
                 //atualiza a lista sem pessoa excluida
                lista = dao.listar();
                Limpar();    
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir");
            }     
        }
    private void Limpar(){
        txtcod.setText("");
        txtnome.setText("");
        SCombocaixa.setSelectedIndex(0);
        posicao=0;
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnteriorActionPerformed
        // TODO add your handling code here:
        if(lista.size()>0){
            posicao=posicao-1;
            Pessoa pessoa = lista.get(posicao);
            txtcod.setText(pessoa.getCodigo().toString());
            txtnome.setText(pessoa.getNome());
            if(pessoa.getSexo().equals("F")){
                SCombocaixa.setSelectedIndex(1);
            }else if(pessoa.getSexo().equals("M")){
                SCombocaixa.setSelectedIndex(2);
            }
        }
    }//GEN-LAST:event_BAnteriorActionPerformed

    private void BProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProximoActionPerformed
        // TODO add your handling code here:
        if(posicao<lista.size()-1){
            posicao = posicao+1;
            Pessoa pessoa = lista.get(posicao);
            txtcod.setText(pessoa.getCodigo().toString());
            txtnome.setText(pessoa.getNome());
            if(pessoa.getSexo().equals("F")){
                SCombocaixa.setSelectedIndex(1);
            }else if(pessoa.getSexo().equals("M")){
                SCombocaixa.setSelectedIndex(2);
            }
        }
    }//GEN-LAST:event_BProximoActionPerformed

    private void BUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUltimoActionPerformed
        // TODO add your handling code here:
        if(lista.size()>0){
            posicao = lista.size();
            Pessoa pessoa = lista.get(posicao-1);
            txtcod.setText(pessoa.getCodigo().toString());
            txtnome.setText(pessoa.getNome());
            if(pessoa.getSexo().equals("F")){
                SCombocaixa.setSelectedIndex(1);
            }else if(pessoa.getSexo().equals("M")){
                SCombocaixa.setSelectedIndex(2);
            }
        }
    }//GEN-LAST:event_BUltimoActionPerformed

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
      // TODO add your handling code here:
        Integer consulta = Integer.parseInt(JOptionPane.showInputDialog("Digite o código da pessoa: "));
        Integer achou = 0;
        Boolean encontrou = false;
        if (consulta != 0) {
            for (Pessoa p : lista) {
                if (consulta == p.getCodigo()) {
                    encontrou = true;
                    txtcod.setText(p.getCodigo().toString());
                    txtnome.setText(p.getNome());
                    switch (p.getSexo()) {
                        case "M":
                            SCombocaixa.setSelectedIndex(1);
                            break;
                        case "F":
                            SCombocaixa.setSelectedIndex(2);
                            break;
                    }
                    posicao = achou;
                    break;
                }
                achou++;
            }
        }
        if (encontrou == false) {
            JOptionPane.showMessageDialog(rootPane, "Pessoa não encontrada. ");
        }
    }//GEN-LAST:event_BConsultarActionPerformed

    private void BLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimparActionPerformed
        // TODO add your handling code here:
        Limpar();
    }//GEN-LAST:event_BLimparActionPerformed

    private void btnListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemActionPerformed
        // TODO add your handling code here:
        PessoaLista listax = new PessoaLista();
        listax.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(txtcod.getText().isEmpty())
        {
                        JOptionPane.showMessageDialog(rootPane, "Registro não informado. ");
        }else
        {
            Pessoa p = new Pessoa();
            p.setCodigo(Integer.parseInt(txtcod.getText()));
            p.setNome(txtnome.getText());
            p.setSexo(SCombocaixa.getSelectedItem().toString());
            
            PessoaDAO dao = new PessoaDAO();
            boolean deucerto;
            deucerto = dao.atualizar(p);
            if(deucerto=true)
            {
                JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso. ");
            }JOptionPane.showMessageDialog(rootPane, "Erro na execução da alteração. ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    private void SCombocaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCombocaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCombocaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaManter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnterior;
    private javax.swing.JButton BCadastra;
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BExcluir;
    private javax.swing.JButton BLimpar;
    private javax.swing.JButton BPrimeiro;
    private javax.swing.JButton BProximo;
    private javax.swing.JButton BUltimo;
    private javax.swing.JComboBox SCombocaixa;
    private javax.swing.JButton btnListagem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
