/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adm;

/**
 *
 * @author Jiovana
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGerenciarP = new javax.swing.JMenuItem();
        menuListarP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGerenciarC = new javax.swing.JMenuItem();
        menuListarC = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1317788420400831019pittsburgh skyline silhouette 600dpi.png"))); // NOI18N

        jMenu1.setText("Pessoa");

        menuGerenciarP.setText("Gerenciar");
        menuGerenciarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarPActionPerformed(evt);
            }
        });
        jMenu1.add(menuGerenciarP);

        menuListarP.setText("Listar");
        menuListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarPActionPerformed(evt);
            }
        });
        jMenu1.add(menuListarP);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cidade");

        menuGerenciarC.setText("Gerenciar");
        menuGerenciarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarCActionPerformed(evt);
            }
        });
        jMenu2.add(menuGerenciarC);

        menuListarC.setText("Listar");
        menuListarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarCActionPerformed(evt);
            }
        });
        jMenu2.add(menuListarC);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGerenciarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarPActionPerformed
        // TODO add your handling code here:
        PessoaManter tela = new PessoaManter();
        //fechar janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
        
    }//GEN-LAST:event_menuGerenciarPActionPerformed

    private void menuListarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarPActionPerformed
        // TODO add your handling code here:
        PessoaLista tela = new PessoaLista();
        //fechar janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_menuListarPActionPerformed

    private void menuGerenciarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarCActionPerformed
        // TODO add your handling code here:
        CidadeManter tela = new CidadeManter();
        //fechar janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_menuGerenciarCActionPerformed

    private void menuListarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarCActionPerformed
        // TODO add your handling code here:
        CidadeListar tela = new CidadeListar();
        //fechar janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_menuListarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuGerenciarC;
    private javax.swing.JMenuItem menuGerenciarP;
    private javax.swing.JMenuItem menuListarC;
    private javax.swing.JMenuItem menuListarP;
    // End of variables declaration//GEN-END:variables
}
